### ISSUE TITLE
Escribir el modulo que genere el PDF

### ISSUE THREAD

**Issue by lrosasr** [cpesfm/API-SAES#3]
- El modulo debera aceptar como entrada un `dict`
- Debe verificar que los datos tengan formato correcto
- El PDF tiene que ser almacenado temporalmente en memoria (en un objeto `bytesIO` tal vez?)

**Comment by oftavira** [comment]
Ya se tiene un generador pdf propuesto, por el momento se proponen las librerias a usar (reportlab & pillow) y la estructura basica, pero se debe presentar una plantilla a llenar.

**Comment by lrosasr** [comment]
Primera version de API/pdf.py creada
